### ISSUE TITLE
Crashes since 4.8.0-Matrix

### ISSUE THREAD

**Issue by dhewg** [kodi-pvr/pvr.iptvsimple#312]
Using 4.8.1-Matrix, but same issue with 4.8.0-Matrix:

dmesg:
```
kodi.sh[2602]: free(): invalid next size (normal)
kernel: audit: type=1701 audit(1574499709.844:2): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2610 comm="kodi.bin" exe="/usr/lib/kodi/kodi.bin" sig=6 res=1
audit[2610]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2610 comm="kodi.bin" exe="/usr/lib/kodi/kodi.bin" sig=6 res=1
kodi.sh[2602]: Aborted (core dumped)
```

crashlog:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xf5c6c2f0 in __GI_abort () at abort.c:79
#2  0xf5cba298 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:181
#3  0xf5cc1c2c in malloc_printerr (str=<optimized out>) at malloc.c:5332
#4  0xf5cc3c40 in _int_free (av=0xf5d8d75c <main_arena>, p=0x2b6e6d0, have_lock=<optimized out>) at malloc.c:4356
#5  0xf5b8ced4 in std::string::assign(std::string const&) () from /usr/lib/libstdc++.so.6
#6  0x006d1690 in CLog::LogString(int, std::string&&) ()
#7  0x006a7df4 in ?? ()
#8  0x005b3f48 in KodiAPI::AddOn::CAddonCallbacksAddon::AddOnLog(void*, ADDON::addon_log, char const*) ()
#9  0xe9603fa0 in ADDON::CHelper_libXBMC_addon::Log(ADDON::addon_log, char const*, ...) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.1
#10 0xe9618d08 in iptvsimple::utilities::Logger::Log(iptvsimple::utilities::LogLevel, char const*, ...) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.1
#11 0xe9602f24 in GetChannelStreamProperties () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.1
#12 0x00475320 in ?? ()
#13 0x0046c300 in PVR::CPVRClient::DoAddonCall(char const*, std::function<PVR_ERROR (KodiToAddonFuncTable_PVR const*)>, bool, bool) const ()
#14 0x0046cea4 in PVR::CPVRClient::GetChannelStreamProperties(std::shared_ptr<PVR::CPVRChannel> const&, PVR::CPVRStreamProperties&) ()
#15 0x004abe28 in PVR::CPVRGUIActions::StartPlayback(CFileItem*, bool) const ()
#16 0x004ad440 in PVR::CPVRGUIActions::SwitchToChannel(std::shared_ptr<CFileItem> const&, bool) const ()
#17 0x0048e2f4 in PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(CGUIMessage&) ()
#18 0x0048e3c8 in PVR::CGUIDialogPVRGuideInfo::OnMessage(CGUIMessage&) ()
#19 0x00657178 in CGUIButtonControl::OnClick() ()
#20 0x0064c2c4 in CGUIButtonControl::OnAction(CAction const&) ()
#21 0x0061dcb4 in CGUIWindow::OnAction(CAction const&) ()
#22 0x00615824 in CGUIWindowManager::HandleAction(CAction const&) const ()
#23 0x0061592c in CGUIWindowManager::OnAction(CAction const&) const ()
#24 0x0056eb38 in CApplication::OnAction(CAction const&) ()
#25 0x0066be6c in CInputManager::ProcessQueuedActions() ()
#26 0x00670328 in CInputManager::Process(int, float) ()
#27 0x0056fd90 in CApplication::FrameMove(bool, bool) ()
#28 0x0060eb88 in CGUIWindowManager::ProcessRenderLoop(bool) ()
#29 0x006442f0 in CGUIDialog::Open_Internal(bool, std::string const&) ()
#30 0x006464a0 in CGUIDialog::Open(std::string const&) ()
#31 0x004a98fc in PVR::CPVRGUIActions::ShowEPGInfo(std::shared_ptr<CFileItem> const&) const ()
#32 0x004d5304 in PVR::CGUIWindowPVRGuideBase::OnMessage(CGUIMessage&) ()
#33 0x004ab4a0 in PVR::CGUIEPGGridContainer::OnClick(int) ()
#34 0x0061dcb4 in CGUIWindow::OnAction(CAction const&) ()
#35 0x00713a70 in CGUIMediaWindow::OnAction(CAction const&) ()
#36 0x004d5c70 in PVR::CGUIWindowPVRBase::OnAction(CAction const&) ()
#37 0x006158c4 in CGUIWindowManager::HandleAction(CAction const&) const ()
#38 0x0061592c in CGUIWindowManager::OnAction(CAction const&) const ()
#39 0x0056eb38 in CApplication::OnAction(CAction const&) ()
#40 0x0066be6c in CInputManager::ProcessQueuedActions() ()
#41 0x00670328 in CInputManager::Process(int, float) ()
#42 0x0056fd90 in CApplication::FrameMove(bool, bool) ()
#43 0x005242d0 in CXBApplicationEx::Run(CAppParamParser const&) ()
#44 0x0068c928 in XBMC_Run ()
#45 0x002ba550 in main ()
```

4.7.1-Matrix works fine

**Comment by phunkyfish** [comment]
Can you give an example M3U entry that causes a crash?

**Comment by phunkyfish** [comment]
Can you try one of these test builds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-313/2/artifacts

Or if you build yourself. This PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/313

**Comment by dhewg** [comment]
Build myself with #313, but it still crashes. It's probably worth mentioning that I'm testing this on libreelec/arm, which e.g. comes with its own ffmpeg patches.
But then again, the backtrace looks more like it's attempting to log from an invalid std:string pointer or something?

```
Thread 1 (Thread 0xf415e010 (LWP 3167)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xf5d452f0 in __GI_abort () at abort.c:79
#2  0xf5d93298 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:181
#3  0xf5d9ac2c in malloc_printerr (str=<optimized out>) at malloc.c:5332
#4  0xf5d9de3c in _int_malloc (av=av@entry=0xf5e6675c <main_arena>, bytes=0, bytes@entry=41) at malloc.c:3736
#5  0xf5d9f6ac in __GI___libc_malloc (bytes=41) at malloc.c:3066
#6  0xf5c1f434 in operator new(unsigned int) () from /usr/lib/libstdc++.so.6
#7  0xf5c644f4 in std::string::_Rep::_S_create(unsigned int, unsigned int, std::allocator<char> const&) () from /usr/lib/libstdc++.so.6
#8  0xf5c6554c in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned int) () from /usr/lib/libstdc++.so.6
#9  0xf5c65604 in std::string::reserve(unsigned int) () from /usr/lib/libstdc++.so.6
#10 0xf5c658e4 in std::string::append(char const*, unsigned int) () from /usr/lib/libstdc++.so.6
#11 0xe9d05c68 in iptvsimple::utilities::Logger::Log(iptvsimple::utilities::LogLevel, char const*, ...) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.2
#12 0xe9ceff24 in GetChannelStreamProperties () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.2
#13 0x00475320 in ?? ()
#14 0x0046c300 in PVR::CPVRClient::DoAddonCall(char const*, std::function<PVR_ERROR (KodiToAddonFuncTable_PVR const*)>, bool, bool) const ()
#15 0x0046cea4 in PVR::CPVRClient::GetChannelStreamProperties(std::shared_ptr<PVR::CPVRChannel> const&, PVR::CPVRStreamProperties&) ()
#16 0x004abe28 in PVR::CPVRGUIActions::StartPlayback(CFileItem*, bool) const ()
#17 0x004ad440 in PVR::CPVRGUIActions::SwitchToChannel(std::shared_ptr<CFileItem> const&, bool) const ()
#18 0x004ad788 in PVR::CPVRGUIActions::PlayMedia(std::shared_ptr<CFileItem> const&) const ()
#19 0x0056cc68 in CApplication::PlayMedia(CFileItem&, std::string const&, int) ()
#20 0x0036bbc0 in ?? ()
#21 0x00371580 in CBuiltins::Execute(std::string const&) ()
#22 0x005653c0 in CApplication::ExecuteXBMCAction(std::string, std::shared_ptr<CGUIListItem> const&) ()
#23 0x00567da8 in CApplication::OnMessage(CGUIMessage&) ()
#24 0x00613a2c in CGUIWindowManager::SendMessage(CGUIMessage&) ()
#25 0x0067c214 in CDirectoryProvider::OnClick(std::shared_ptr<CGUIListItem> const&) ()
#26 0x006573b0 in CGUIBaseContainer::OnClick(int) ()
#27 0x0061dcb4 in CGUIWindow::OnAction(CAction const&) ()
#28 0x006158c4 in CGUIWindowManager::HandleAction(CAction const&) const ()
#29 0x0061592c in CGUIWindowManager::OnAction(CAction const&) const ()
#30 0x0056eb38 in CApplication::OnAction(CAction const&) ()
#31 0x0066be6c in CInputManager::ProcessQueuedActions() ()
#32 0x00670328 in CInputManager::Process(int, float) ()
#33 0x0056fd90 in CApplication::FrameMove(bool, bool) ()
#34 0x005242d0 in CXBApplicationEx::Run(CAppParamParser const&) ()
#35 0x0068c928 in XBMC_Run ()
#36 0x002ba550 in main ()
```

**Comment by dhewg** [comment]
Last line of kodi.log:
```
DEBUG: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - GetChannelStreamProperties - inputstream URL: https://unilivemtveu-lh.akamaihd.net/i/mtvde_1@134922/index_3500_av-p.m3u8
```

**Comment by phunkyfish** [comment]
Can you supply the line of your M3U that fails with this error?

It’s a log line alright. Just need to track down which one.

**Comment by dhewg** [comment]
What do you mean?

With this
```
$ cat settings.xml|grep -v default
<settings version="2">
    <setting id="epgUrl">https://rytec.ricx.nl/epg_data/rytecDE_Basic.gz</setting>
    <setting id="m3uRefreshMode">1</setting>
    <setting id="m3uUrl">http://bit.ly/kn-kodi</setting>
</settings>
```

It crashes instantly when selecting a channel, the above mentioned m3u8 would be line 31 of the m3u. But it crashes almost everytime, doesn't seem to matter much which channel I try

**Comment by phunkyfish** [comment]
Can you post a full debug log capturing the error? So:

1) enable debug mode
2) restart kodi
3) reproduce the error
4) post the full log using a paste site.

**Comment by dhewg** [comment]
https://ybin.me/p/0e427cb9c7594bc3#C61jsxyITLMrQGKCsKgNRyKSgH9lOlpSW6sypliQ01g=

**Comment by phunkyfish** [comment]
Ok, I think I have it, please try this testbuild: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-313/3/artifacts

**Comment by dhewg** [comment]
Thanks, that works!

**Comment by dhewg** [comment]
While it doesn't crash now, there's another problem:
Upon the first m3u playlist refresh after starting kodi:
```
2019-11-24 10:05:58.893 T:3325  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadPlayList Playlist Loaded - 522 (ms)
2019-11-24 10:05:58.893 T:3325  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadPlayList - Loaded 230 channels.
```
its then reloading the epg in a seemingly endless loop:
```
2019-11-24 10:06:00.180 T:3325  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadChannelEpgs - Loaded '44' EPG channels.
2019-11-24 10:06:00.352 T:3325  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadEpgEntries - Loaded '0' EPG entries.
2019-11-24 10:06:00.515 T:3325  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadEPG - EPG Loaded - 1613 (ms)
2019-11-24 10:06:01.836 T:3331  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadChannelEpgs - Loaded '44' EPG channels.
2019-11-24 10:06:02.054 T:3331  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadEpgEntries - Loaded '5702' EPG entries.
2019-11-24 10:06:02.214 T:3331  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadEPG - EPG Loaded - 1288 (ms)
```
and on and on and...

**Comment by phunkyfish** [comment]
If you clear your PVR DB does it still happen? Very strange that the number of channels stays the same but the EPG entry count differs.

Does debug mode give any more info?

**Comment by phunkyfish** [comment]
Ok, I can reproduce this. What interval do you have set for refresh?

**Comment by phunkyfish** [comment]
Nevermind. Please try this PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/314

Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-314/1/artifacts

**Comment by dhewg** [comment]
Yup, that's fixed too, thanks!
