### ISSUE TITLE
okay, here's the output

### ISSUE THREAD

**Issue by Jr7000750** [kodi-pvr/pvr.iptvsimple#444]
okay, here's the output
```log
►  start     Starting eDEX-UI v2.2.2
i  info      With Node 10.11.0 and Electron 4.2.0
i  info      Renderer is Chrome 69.0.3497.128
►  Startup   Initialized timer...
i  info      Base config dir is C:\Users\ygy\AppData\Roaming\eDEX-UI
[ ]  pending   Loading settings file...
√  success   Settings loaded!
[ ]  pending   Creating new terminal process on port 3000
(node:6736) UnhandledPromiseRejectionWarning: Error: Cannot create process, error code: 267
    at new WindowsPtyAgent (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:76:43)
    at new WindowsTerminal (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:181:11)
(node:6736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I guess the warning is the error, and I'll test if PowerShell.exe has the same warning.

UPDATE: Sorry, this is NOT the correct log, I edited the settings wrong to get this log, but It differs from I think.

UPDATE 2: The correct output is the same as above, I dunno why.

__Originally posted by @2403772980ygy in https://github.com/GitSquared/edex-ui/issues/698#issuecomment-592791762__

**Comment by phunkyfish** [comment]
Why are you posting this here?
