### ISSUE TITLE
Catchup start date end date

### ISSUE THREAD

**Issue by tonebiclas** [kodi-pvr/pvr.iptvsimple#620]
Is there way with this addon pvr to create something like this?
![image](https://user-images.githubusercontent.com/19857190/180916185-d8fee730-36af-4b32-9d46-7902ebade31a.png)
image from ott navigator faq https://github.com/ottnav/ottnav.github.io/blob/main/faq.md

Example:

`
.....&start=${start-year}-${start-mon}-${start-day}T${start-hour}:${start-min}:${start-sec}Z&end=${end-year}-${end-mon}-${end-day}T${end-hour}:${end-min}:${end-sec}Z
`

**Comment by tonebiclas** [comment]
Would it be enough if those "variables" showed could be added here and thats it?
https://github.com/kodi-pvr/pvr.iptvsimple/blob/40f71f781fe2792a13cf9c3475156e587a2366ec/src/iptvsimple/CatchupController.cpp#L347



Also, i have one question related to this, that comes after.

Lets say my programme epg for one channel is like:
`<programme start="20220725235500 +0100" stop="20220726000500 +0100" channel="CART">........`

how can I make my catchup contain a date, with one hour less.
`start=2022-07-25T22:55:00Z&end=....`
and in the pvr grid show +01 as for example 
`2022 07 25 23:55:00`

**Comment by phunkyfish** [comment]
To get the one hour less you need to set the time zone information in the addon. Just read the README for instructions on how to do this.

For the catchup format you need can you give a example URL you need it to look like.

**Comment by phunkyfish** [comment]
You should convert the query string used by your provider to one that works with this addon.

**Comment by tonebiclas** [comment]
Example how it ends.
![image](https://user-images.githubusercontent.com/19857190/181065285-0b5c3a7a-54d9-4433-ae1a-72c7054b530c.png)

I tried to convert with a proxy i coded, redirecting with 301 ... it works with ott navigator and browser and playlist loader i did for kodi
but not with this pvr

the pvr is redirecting complety  to the provider url in the Location header
http://xpto.com/channel.m3u8?start=....&end=.....
then that url contains this
`#EXT-X-STREAM-INF:BANDWIDTH=3000000,CODECS="mp4a.40.2,avc1.640029",RESOLUTION=1280x720,FRAME-RATE=50
index.m3u8/...........`

but then, it doesnt redirect go for `http://xpto.com/index.m3u8/.....`
if the proxy is 127.0.0.1:3333 it go like: `http://127.0.0.1:3333/index.m3u8/....`

so it expects the proxy to provide the content when i already redirected, once redirected it should not need the proxy anymore.

makes sense?

**Comment by tonebiclas** [comment]
Takes this as example: https://sic.live.impresa.pt/sicnot.m3u8
 
#EXTINF:0 tvg-id="SICNOT" tvg-name="SICNOT",SIC Noticias
http://127.0.0.1:3333/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4


Proxy code:
```python
#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler, HTTPServer
import logging
import base64
from urllib.parse import urlparse, parse_qsl

class S(BaseHTTPRequestHandler):
    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        print(self.path)
        p = urlparse(self.path)
        try:
            params = dict(parse_qsl(p.query))
        except:
            params = {}
    
        url = base64.b64decode( params['query'] ).decode('utf8')
        print("URL:", url)
        self.send_response(301)
        print('Redirecting to:', url)
        self.send_header('Location', url)
        self.end_headers()

    '''
    def do_POST(self):
        content_length = int(self.headers['Content-Length']) # <--- Gets the size of data
        post_data = self.rfile.read(content_length) # <--- Gets the data itself
        logging.info("POST request,\nPath: %s\nHeaders:\n%s\n\nBody:\n%s\n",
                str(self.path), str(self.headers), post_data.decode('utf-8'))

        self._set_response()
        self.wfile.write("POST request for {}".format(self.path).encode('utf-8'))
    '''
def run(server_class=HTTPServer, handler_class=S, port=3333):
    logging.basicConfig(level=logging.INFO)
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    logging.info('Starting httpd...\n')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    logging.info('Stopping httpd...\n')

if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```


TESTED AGAINST THE PVR:
LOG..........:
```
127.0.0.1 - - [26/Jul/2022 19:00:12] code 501, message Unsupported method ('HEAD')
127.0.0.1 - - [26/Jul/2022 19:00:12] "HEAD /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 501 -
127.0.0.1 - - [26/Jul/2022 19:00:12] code 501, message Unsupported method ('HEAD')
127.0.0.1 - - [26/Jul/2022 19:00:12] "HEAD /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 501 -
/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8
127.0.0.1 - - [26/Jul/2022 19:00:12] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8

not redirected?!?!!!!!!!!!!

/sicnot/46188/sicnot20220726T175914_00019.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59471)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\meohttp\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/sicnot/46188/sicnot20220726T175929_00020.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59472)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\meohttp\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/sicnot/46189/sicnot20220726T175944_00001.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59473)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\meohttp\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8


*Oh finaly it will play as redirected?! but doesnt happen the same with my provider link ... and it took 16 seconds to reach here lol*

127.0.0.1 - - [26/Jul/2022 19:00:28] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8
```

```
TESTED AGAINST VLC
LOG.............:

INFO:root:Starting httpd...

/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8
127.0.0.1 - - [26/Jul/2022 19:17:39] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8

```

^^^^^^^^^^^ this should be the behaviour

**Comment by tonebiclas** [comment]
Takes this as example: https://sic.live.impresa.pt/sicnot.m3u8
 
#EXTINF:0 tvg-id="SICNOT" tvg-name="SICNOT",SIC Noticias
http://127.0.0.1:3333/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4


Proxy code:
```python
#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler, HTTPServer
import logging
import base64
from urllib.parse import urlparse, parse_qsl

class S(BaseHTTPRequestHandler):
    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        print(self.path)
        p = urlparse(self.path)
        try:
            params = dict(parse_qsl(p.query))
        except:
            params = {}
    
        url = base64.b64decode( params['query'] ).decode('utf8')
        print("URL:", url)
        self.send_response(301)
        print('Redirecting to:', url)
        self.send_header('Location', url)
        self.end_headers()

    '''
    def do_POST(self):
        content_length = int(self.headers['Content-Length']) # <--- Gets the size of data
        post_data = self.rfile.read(content_length) # <--- Gets the data itself
        logging.info("POST request,\nPath: %s\nHeaders:\n%s\n\nBody:\n%s\n",
                str(self.path), str(self.headers), post_data.decode('utf-8'))

        self._set_response()
        self.wfile.write("POST request for {}".format(self.path).encode('utf-8'))
    '''
def run(server_class=HTTPServer, handler_class=S, port=3333):
    logging.basicConfig(level=logging.INFO)
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    logging.info('Starting httpd...\n')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    logging.info('Stopping httpd...\n')

if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```


TESTED AGAINST THE PVR:
LOG..........:
```
127.0.0.1 - - [26/Jul/2022 19:00:12] code 501, message Unsupported method ('HEAD')
127.0.0.1 - - [26/Jul/2022 19:00:12] "HEAD /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 501 -
127.0.0.1 - - [26/Jul/2022 19:00:12] code 501, message Unsupported method ('HEAD')
127.0.0.1 - - [26/Jul/2022 19:00:12] "HEAD /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 501 -
/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8
127.0.0.1 - - [26/Jul/2022 19:00:12] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8

not redirected?!?!!!!!!!!!!

/sicnot/46188/sicnot20220726T175914_00019.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59471)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\proxy\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/sicnot/46188/sicnot20220726T175929_00020.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59472)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\proxy\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/sicnot/46189/sicnot20220726T175944_00001.ts
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59473)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Users\user\Desktop\proxy\proxy.py", line 25, in do_GET
    url = base64.b64decode( params['query'] ).decode('utf8')
KeyError: 'query'
----------------------------------------
/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8


*Oh finaly it will play as redirected?! but doesnt happen the same with my provider link ... and it took 16 seconds to reach here lol*

127.0.0.1 - - [26/Jul/2022 19:00:28] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8
```

```
TESTED AGAINST VLC
LOG.............:

INFO:root:Starting httpd...

/?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4
URL: https://sicnot.live.impresa.pt/sicnot.m3u8
127.0.0.1 - - [26/Jul/2022 19:17:39] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8

```

^^^^^^^^^^^ this should be the behaviour

**Comment by phunkyfish** [comment]
@basilgello has written many proxies using the add-on and can likely give better advice than I would.

Please note that changing the add-on behaviour to suit the redirection logic in your proxy is not not really an option.

**Comment by tonebiclas** [comment]
why not? isnt this the normal behaviour for a 301 redirect with location header?
what the addon is doing that changing the behaviour makes it not really an option?

**Comment by basilgello** [comment]
@tonebiclas you definitely have an issue with your script, because my proxy server does the 301 redirect and both ffmpeg or curl follow it.

I quickly looked at your script and here is the issue spotted:

1. I'd advise against passing raw URL in the encoded form. This is basically an open redirect and it can posess a security risk if an external attacker reuses your server as a proxy. Instead, pass the id and append it to the tv server URL after you validate that the content is meaningful. Like `http://xhost/tvprovider/channel?id=100&ts=202011020212` for catchup or without the `ts` part for live TV. Also, think about HTTPS and passwprd-based auth if you ever decide to face it open Internet.

2. Why do you need rewriting m3u8 playlist or proxying ts segments? The only need for such transforms is custom restrictions set by TV provider, like keepalive headers. Basic 301 should work.

3. Check your code once more, it fails to decode your base64-encoded string.

**Comment by basilgello** [comment]
Answering your question:

> why not? isnt this the normal behavior for a 301 redirect with location header?

As I mentioned, 30x redirects work for both libcurl (think `inputstream.adaptive`) and ffmpeg (kodi player and `inputstream.ffmpegdirect`. And 16 seconds to make a single HTTP response? Are you running it on RPi???

**Comment by tonebiclas** [comment]
ofc it fails to decoded bcuz i dont want this to happen when there is REDIRECT happening:
/sicnot/46188/sicnot20220726T175929_00020.ts (WHY trying to open the url and get the segment?)
the pvr is "dumb" to not think i said "REDIRECT NOW" hahaha

**Comment by tonebiclas** [comment]
> inputstream.ffmpegdirect

if i set kodi props with this it redirects, its what u meant?

**Comment by tonebiclas** [comment]
@basilgello And 16 seconds to make a single HTTP response? Are you running it on RPi???

No, kodi in Windows with high-end machine lets say lol.
in that log of pvr:
it redirects, then it try to open the m3u8 (maybe normal behavior of pvr, read the m3u8 and get the segment) instead of redirect
the segment url then is passed to the proxy
ofc error happens thats why i said in the last comment. 
and after 16 seconds from the first request it redirets without trying to read the m3u8  like second attempt!

**Comment by tonebiclas** [comment]
@basilgello And 16 seconds to make a single HTTP response? Are you running it on RPi???

No, kodi in Windows with high-end machine lets say lol.
in that log of pvr:

1 - it redirects
`
127.0.0.1 - - [26/Jul/2022 19:00:12] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8
`
then instead of start playing as it should, it try to open the m3u8 (maybe normal behavior of pvr, read the m3u8 and get the segment) instead of redirect
/sicnot/46188/sicnot20220726T175914_00019.ts

the segment url then is passed to the proxy

ofc error happens thats why i said in the last comment. 
and after 16 seconds counting from the first request date it redirects without trying to read the m3u8  just like an second attempt!

**Comment by tonebiclas** [comment]
@basilgello And 16 seconds to make a single HTTP response? Are you running it on RPi???

No, Windows. with high-end machine :P

Lemme try to explain...
127.0.0.1 - - [26/Jul/2022 19:00:12] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8

After this request the proxy should not receive more requests, and hls link should be played. i dont want to rewrite lol

But pvr decides to open the m3u8 and get the segments
/sicnot/46188/sicnot20220726T175914_00019.ts
/sicnot/46188/sicnot20220726T175929_00020.ts
...
ofc error happens to decode b64 bcuz it doesnt contain query parameter...

somehow after the errors it tries second attempt, and plays!? but after 16 seconds
127.0.0.1 - - [26/Jul/2022 19:00:28] "GET /?query=aHR0cHM6Ly9zaWNub3QubGl2ZS5pbXByZXNhLnB0L3NpY25vdC5tM3U4 HTTP/1.1" 301 -
Redirecting to: https://sicnot.live.impresa.pt/sicnot.m3u8 


This second attempt doesnt happen in my provider url!
even so, 16 seconds is not good.. its not my machine that is slow, haha! :P

**Comment by basilgello** [comment]
If you specify the url and the server returns 301 Moved Temporary or 302 Found, Kodi will follow the redirect. Just need to check if cookies can be set this,way

**Comment by basilgello** [comment]
Aha. So that means that your redirect still points to your server. Try opening a dev tools in browser and paste your link into address bar and show the scrren

**Comment by tonebiclas** [comment]
@basilgello 
![image](https://user-images.githubusercontent.com/19857190/181112062-77611925-e347-45ac-9739-58104048e166.png)

**Comment by tonebiclas** [comment]
@basilgello VLC
![image](https://user-images.githubusercontent.com/19857190/181113093-3dcaf956-e949-4ec6-9069-818946bc2ad2.png)

![image](https://user-images.githubusercontent.com/19857190/181113576-9617cadf-a0b0-49de-9f4a-00f5d57e8f5a.png)

**Comment by tonebiclas** [comment]
> Aha. So that means that your redirect still points to your server. Try opening a dev tools in browser and paste your link into address bar and show the scrren

Yes. The problem is the redirect still points to the proxy server but only in the pvr :D

**Comment by basilgello** [comment]
The Impresa TV links throw 403 on my side. Let me prepare a working example for IPTV Simple tonight :)
