### ISSUE TITLE
KODI crashes when the EPG file in playlist is archived in .gz format.

### ISSUE THREAD

**Issue by tezzzar** [kodi-pvr/pvr.iptvsimple#738]
crashes on Raspberry pi 3B+

https://mater.com.ua/ip/iptv-s-2021.m3u

**Comment by phunkyfish** [comment]
Crash log and fill debug log please

**Comment by phunkyfish** [comment]
Note that file works ok for me. You don’t even state was version or flavour of kodi you are using.

**Comment by arthur-liberman** [comment]
Hi @phunkyfish,
I have a similar issue, which doesn't happen every time the EPG is filled, but occasionally.
IPTV Simple crashes Kodi, making it restart.
Versions 20.11.0 and 19.2.2 are both affected, with a similar crash.
```
Thread 1 (Thread 0x8c2f92c0 (LWP 3830)):
#0  0xb2bc4860 in ?? () from /usr/lib/libc.so.6
#1  0xb2b814b8 in raise () from /usr/lib/libc.so.6
#2  0xb2b6d784 in abort () from /usr/lib/libc.so.6
#3  0xb2a030f0 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/libstdc++.so.6
#4  0xb2a00c94 in ?? () from /usr/lib/libstdc++.so.6
#5  0xb2a00d14 in std::terminate() () from /usr/lib/libstdc++.so.6
#6  0xb2a01048 in __cxa_throw () from /usr/lib/libstdc++.so.6
#7  0xb2a016a4 in operator new(unsigned int) () from /usr/lib/libstdc++.so.6
#8  0xb2a9bf80 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned int, unsigned int, char const*, unsigned int) () from /usr/lib/libstdc++.so.6
#9  0x9863f6d8 in iptvsimple::utilities::FileUtils::GzipInflate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.20.11.0
#10 0x98615a50 in iptvsimple::Epg::FillBufferFromXMLTVData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.20.11.0
#11 0x98618614 in iptvsimple::Epg::LoadEPG(long, long) () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.20.11.0
#12 0x986189a4 in iptvsimple::Epg::ReloadEPG() () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.20.11.0
#13 0x985ee3dc in ?? () from /storage/.kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.20.11.0
#14 0xb2a2d920 in ?? () from /usr/lib/libstdc++.so.6
#15 0xb2bc2bdc in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
After Kodi restarts, the EPG is loaded.
My theory is perhaps the system runs out of memory. The EPG .gz is about 35MB and the inflated file is over 300MB.

I looked through the code, and can't put my finger on where exactly this crash occurs, but the code looks like it can and should be optimized? Loading 350MB byte by byte into a std::string object doesn't seem very efficient to me?

**Comment by phunkyfish** [comment]
I don’t disagree with you. It works this way today because it’s always been this way likely. I guess back in the old days EPG files were relatively small.

If you’d like to contribute the optimisation, that would be be great.

**Comment by arthur-liberman** [comment]
@phunkyfish 
I made some more tests. I fed the addon an already extracted EPG to work around the crash, but it was not resolved, it just crashed somewhere down the line.
I found one thing to be correlated to this issue. I have set the addon to update the channel list once a day, from a local file.
The crash always occurred at the time I set for the channel list to refresh.
It seems that the EPG is refreshed after (or during?) the channel list refresh, which can eventually lead to this issue.
I suspect that it could be caused by lack of memory on the device (although it has 4GB of RAM) when the channels and epg are reloaded at the same time.
A while ago I disabled channel refresh, and it seems to have stopped the crashes from happening again.

**Comment by phunkyfish** [comment]
Hmmm, I wonder if we can ignore epg refresh requests when the channels are being refreshed.
